### ISSUE TITLE
Input features permitted

### ISSUE THREAD

**Issue by Batene** [iarai/NeurIPS2022-traffic4cast#3]
Dear organizing team,

apart from the 4 loop counter data points, is it really NOT allowed to use additional information (edge attributes such as oneway, tunnel, lanes, etc.) (In the task description, you write "Given one hour of sparse **_loop count data only_** the task is to predict the congestion classification for all road segments 15 minutes into the future.")
Using the congestion labels belonging to the 4 time intervalls covered by the input is not allowed as these labels are coming from the GPS data? 
Thank you very much in advance for your help!

**Comment by chenkins** [comment]
@Batene The congestion labels (and the dynamic GPS data they are derived from) are withheld for the test set, you will only get the vehicle count data as input.

See: https://github.com/iarai/NeurIPS2022-traffic4cast/blob/main/README_DATA_SPECIFICATION.md#testlondoninputcounters_testparquet

See also https://github.com/iarai/NeurIPS2022-traffic4cast#folder-structure
```
For each city, we're using approx. 6 months of data, interleaving training and test data on a weekly basis (1 week of training and 1 week for test)
```

Happy Coding!
Christian

**Comment by chenkins** [comment]
@Batene To address your recent questions regarding whether participants can use additional data for their models we have updated the formal Terms and Conditions for the competition. You will be asked to accept them when you next visit the website. Please find the updated paragraph below.

In a nutshell, if you can think of a way to make your models better by using additional data, that’s great! For fairness to all, however, these data must be equally available to use in the competition to everyone taking part. That means the data must be publicly accessible, and they must be released under a license that allows all participants to use them for this competition.

We look forward to seeing your most creative models succeed!   Please document any dependencies on external data or code for your final submission to the repository including code for data prep and modelling so that others can build on your work.

Happy Coding!
Christian


> 4.27 Participants are tasked with creating a solution for each challenge during the Competition. All proposed solutions and case studies should be built based on the data provided by each Data Provider (“Data Sets”) or any other data the Organizer makes available for Competition Challenges via the Organizer’s Website to all Participants plus optionally any other open data that publicly available and that is free to be used by all Participants for this Competition.
